services:
  devcontainer:
    container_name: the-local-setup
    image: the-local-setup:latest
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - ssh
        - sshpub
    volumes:
      - ./pv:/home/pv/pv
    ports:
      - "3000:3000"
      - "6006:6006"
      - "8080:8080"

secrets:
  ssh:
    file: ssh/id_pv
  sshpub:
    file: ssh/id_pv.pub
